# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: warehouse.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'warehouse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwarehouse.proto\x12\tlogistics\"H\n\x04Item\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x03\"/\n\x0e\x41\x64\x64ItemRequest\x12\x1d\n\x04item\x18\x01 \x01(\x0b\x32\x0f.logistics.Item\"0\n\x0f\x41\x64\x64ItemResponse\x12\x1d\n\x04item\x18\x01 \x01(\x0b\x32\x0f.logistics.Item\"U\n\x11UpdateItemRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x03\"3\n\x12UpdateItemResponse\x12\x1d\n\x04item\x18\x01 \x01(\x0b\x32\x0f.logistics.Item\".\n\x0fTakeItemRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x03\"1\n\x10TakeItemResponse\x12\x1d\n\x04item\x18\x01 \x01(\x0b\x32\x0f.logistics.Item\"\x1f\n\x10QueryItemRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\"2\n\x11QueryItemResponse\x12\x1d\n\x04item\x18\x01 \x01(\x0b\x32\x0f.logistics.Item2\xac\x02\n\x10InventoryService\x12@\n\x07\x41\x64\x64Item\x12\x19.logistics.AddItemRequest\x1a\x1a.logistics.AddItemResponse\x12I\n\nUpdateItem\x12\x1c.logistics.UpdateItemRequest\x1a\x1d.logistics.UpdateItemResponse\x12\x43\n\x08TakeItem\x12\x1a.logistics.TakeItemRequest\x1a\x1b.logistics.TakeItemResponse\x12\x46\n\tQueryItem\x12\x1b.logistics.QueryItemRequest\x1a\x1c.logistics.QueryItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'warehouse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM']._serialized_start=30
  _globals['_ITEM']._serialized_end=102
  _globals['_ADDITEMREQUEST']._serialized_start=104
  _globals['_ADDITEMREQUEST']._serialized_end=151
  _globals['_ADDITEMRESPONSE']._serialized_start=153
  _globals['_ADDITEMRESPONSE']._serialized_end=201
  _globals['_UPDATEITEMREQUEST']._serialized_start=203
  _globals['_UPDATEITEMREQUEST']._serialized_end=288
  _globals['_UPDATEITEMRESPONSE']._serialized_start=290
  _globals['_UPDATEITEMRESPONSE']._serialized_end=341
  _globals['_TAKEITEMREQUEST']._serialized_start=343
  _globals['_TAKEITEMREQUEST']._serialized_end=389
  _globals['_TAKEITEMRESPONSE']._serialized_start=391
  _globals['_TAKEITEMRESPONSE']._serialized_end=440
  _globals['_QUERYITEMREQUEST']._serialized_start=442
  _globals['_QUERYITEMREQUEST']._serialized_end=473
  _globals['_QUERYITEMRESPONSE']._serialized_start=475
  _globals['_QUERYITEMRESPONSE']._serialized_end=525
  _globals['_INVENTORYSERVICE']._serialized_start=528
  _globals['_INVENTORYSERVICE']._serialized_end=828
# @@protoc_insertion_point(module_scope)
